//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyNhaHang.Models {
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.Runtime.CompilerServices;

    public partial class Ban : INotifyPropertyChanged {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Ban() {
            this.HoaDons = new HashSet<HoaDon>();
        }

        private string _Id;
        private string _Name;
        private string _IdTableType;
        private string _IdKhuVuc;
        private int _IdTinhTrang;
        private Nullable<int> _Status;
        private Nullable<System.DateTime> _CreatedAt;
        private Nullable<System.DateTime> _ModifiedAt;
        public KhuVuc _KhuVuc;

        public TableType _TableType;
        public TinhTrang _TinhTrang;

        public string Id {
            get { return _Id; }
            set { _Id = value; OnPropertyChanged("Id"); }
        }

        public string Name {
            get { return _Name; }
            set { _Name = value; OnPropertyChanged("Name"); }
        }
        public string IdTableType {
            get { return _IdTableType; }
            set { _IdTableType = value; OnPropertyChanged("IdTableType"); }
        }
        public string IdKhuVuc {
            get { return _IdKhuVuc; }
            set { _IdKhuVuc = value; OnPropertyChanged("IdKhuVuc"); }
        }
        public int IdTinhTrang {
            get { return _IdTinhTrang; }
            set { _IdTinhTrang = value; OnPropertyChanged("IdTinhTrang"); }
        }
        public Nullable<int> Status {
            get { return _Status; }
            set { _Status = value; OnPropertyChanged("Status"); }
        }
        public Nullable<System.DateTime> CreatedAt {
            get { return _CreatedAt; }
            set { _CreatedAt = value; OnPropertyChanged("CreatedAt"); }
        }
        public Nullable<System.DateTime> ModifiedAt {
            get { return _ModifiedAt; }
            set { _ModifiedAt = value; OnPropertyChanged("ModifiedAt"); }
        }
        public virtual KhuVuc KhuVuc {
            get { return _KhuVuc; }
            set { _KhuVuc = value; OnPropertyChanged("KhuVuc"); }
        }
        public virtual TableType TableType {
            get { return _TableType; }
            set { _TableType = value; OnPropertyChanged("TableType"); }
        }
        public virtual TinhTrang TinhTrang {
            get { return _TinhTrang; }
            set { _TinhTrang = value; OnPropertyChanged("TinhTrang"); }
        }

        public event PropertyChangedEventHandler PropertyChanged;
        protected void OnPropertyChanged([CallerMemberName] string name = null) {
            PropertyChanged?.Invoke(this, new PropertyChangedEventArgs(name));
        }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HoaDon> HoaDons { get; set; }
    }
}
