//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyNhaHang.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.Runtime.CompilerServices;

    public partial class ChiTietHoaDon : INotifyPropertyChanged {
        private double _Quantity;
        private Mon _Mon;
        private HoaDon _HoaDon;
        private int _Id;
        private string _IdHoaDon;
        private string _IdMon;
        private double _PriceBan;
        private double _Amount;
        private string _GhiChu;
        private Nullable<System.DateTime> _CreatedAt;
        private Nullable<System.DateTime> _ModifiedAt;



        public int Id { get { return _Id; } set { _Id = value; OnPropertyChanged("Id"); } }
        public string IdHoaDon { get { return _IdHoaDon; } set { _IdHoaDon = value; OnPropertyChanged("IdHoaDon"); } }
        public string IdMon { get { return _IdMon; } set { _IdMon = value; OnPropertyChanged("IdMon"); } }
        public double Quantity { get { return _Quantity; } set { _Quantity = value; OnPropertyChanged("Quantity"); } }
        public double PriceBan { get { return _PriceBan; } set { _PriceBan = value; OnPropertyChanged("PriceBan"); } }
        public double Amount { get { return _Amount; } set { _Amount = value; OnPropertyChanged("Amount"); } }
        public string GhiChu { get { return _GhiChu; } set { _GhiChu = value; OnPropertyChanged("GhiChu"); } }
        public Nullable<System.DateTime> CreatedAt { get { return _CreatedAt; } set { _CreatedAt = value; OnPropertyChanged("CreatedAt"); } }
        public Nullable<System.DateTime> ModifiedAt { get { return _ModifiedAt; } set { _ModifiedAt = value; OnPropertyChanged("ModifiedAt"); } }
        public virtual HoaDon HoaDon { get { return _HoaDon; } set { _HoaDon = value; OnPropertyChanged("HoaDon"); } }
        public virtual Mon Mon { get { return _Mon; } set { _Mon = value; OnPropertyChanged("Mon"); } }

        public event PropertyChangedEventHandler PropertyChanged;
        protected void OnPropertyChanged([CallerMemberName] string name = null) {
            PropertyChanged?.Invoke(this, new PropertyChangedEventArgs(name));
        }
    }
}
