//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyNhaHang.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class HuyMon
    {
        public int Id { get; set; }
        public string IdMon { get; set; }
        public int IdUser { get; set; }
        public string IdLiDo { get; set; }
        public System.DateTime Ngay { get; set; }
        public Nullable<System.TimeSpan> Gio { get; set; }
        public int IdCa { get; set; }
        public Nullable<int> TinhTrangGiaoCa { get; set; }
        public Nullable<int> MaLSBGC { get; set; }
    
        public virtual Ca Ca { get; set; }
        public virtual LiDo LiDo { get; set; }
        public virtual Mon Mon { get; set; }
        public virtual User User { get; set; }
    }
}
