//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyNhaHang.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Kho
    {
        public int Id { get; set; }
        public string IdMon { get; set; }
        public Nullable<int> SoLuongDauKi { get; set; }
        public Nullable<int> SoLuongNhapMoi { get; set; }
        public Nullable<int> SoLuongTon { get; set; }
        public int Status { get; set; }
        public Nullable<System.DateTime> CreatedAt { get; set; }
        public Nullable<System.DateTime> ModifiedAt { get; set; }
    
        public virtual Mon Mon { get; set; }
    }
}
