//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyNhaHang.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LichSuBanGiaoCa
    {
        public int Id { get; set; }
        public System.DateTime ThoiGianTu { get; set; }
        public System.DateTime ThoiGianDen { get; set; }
        public string CaGiao { get; set; }
        public string CaNhan { get; set; }
        public int TienTiepNhanCaTruoc { get; set; }
        public int TienHoaDon { get; set; }
        public int TienPhieuThu { get; set; }
        public int TienPhieuChi { get; set; }
        public int TienThucThuCa { get; set; }
        public int TienGiaoQuanLy { get; set; }
        public int TienGiaoCa { get; set; }
        public int TienThucTeGiaoCa { get; set; }
        public int TienChenhLech { get; set; }
        public string GhiChu { get; set; }
        public Nullable<System.DateTime> CreatedAt { get; set; }
        public Nullable<System.DateTime> ModifiedAt { get; set; }
    }
}
