//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyNhaHang.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LichSuHoaDonThanhToan
    {
        public int Id { get; set; }
        public string IdHoaDon { get; set; }
        public Nullable<int> SoTienNo { get; set; }
        public Nullable<int> SoTienTra { get; set; }
        public Nullable<int> SoTienConLai { get; set; }
        public string GhiChu { get; set; }
        public Nullable<System.DateTime> Ngay { get; set; }
        public Nullable<System.TimeSpan> Gio { get; set; }
    
        public virtual HoaDon HoaDon { get; set; }
    }
}
