//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyNhaHang.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LuuKhuyenMai
    {
        public int Id { get; set; }
        public string IdHoaDon { get; set; }
        public string IdMon { get; set; }
        public int IdUser { get; set; }
        public int IdCa { get; set; }
        public int Quantity { get; set; }
        public string GhiChu { get; set; }
        public Nullable<int> isGift { get; set; }
        public Nullable<System.DateTime> CreatedAt { get; set; }
        public Nullable<System.DateTime> ModifiedAt { get; set; }
    
        public virtual Ca Ca { get; set; }
        public virtual HoaDon HoaDon { get; set; }
        public virtual Mon Mon { get; set; }
        public virtual User User { get; set; }
    }
}
