//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyNhaHang.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.Runtime.CompilerServices;

    public partial class Mon : INotifyPropertyChanged {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Mon()
        {
            this.ChiTietHoaDons = new HashSet<ChiTietHoaDon>();
            this.ChiTietHoaDonTemps = new HashSet<ChiTietHoaDonTemp>();
            this.ChiTietPhieuNhaps = new HashSet<ChiTietPhieuNhap>();
            this.HuyMons = new HashSet<HuyMon>();
            this.Khoes = new HashSet<Kho>();
            this.LuuKhuyenMais = new HashSet<LuuKhuyenMai>();
            this.SanPhamKhuyenMais = new HashSet<SanPhamKhuyenMai>();
        }

        private string _Id;
        private string _Name;
        private Nullable<double> _Price;
        private Nullable<double> _PriceInput;
        private string _IdDanhMuc;
        private int _IdUnit;
        private string _IdMayIn;
        private Nullable<int> _Status;
        private Nullable<System.DateTime> _CreatedAt;
        private Nullable<System.DateTime> _ModifiedAt;


        public string Id { get { return _Id; }set { _Id = value; OnPropertyChanged("Id"); } }
        public string Name { get { return _Name; } set { _Name = value; OnPropertyChanged("Name"); } }
        public Nullable<double> Price { get { return _Price; } set { _Price = value; OnPropertyChanged("Price"); } }
        public Nullable<double> PriceInput { get { return _PriceInput; } set { _PriceInput = value; OnPropertyChanged("PriceInput"); } }
        public string IdDanhMuc { get { return _IdDanhMuc; } set { _IdDanhMuc = value; OnPropertyChanged("IdDanhMuc"); } }
        public int IdUnit { get { return _IdUnit; } set { _IdUnit = value; OnPropertyChanged("IdUnit"); } }
        public string IdMayIn { get { return _IdMayIn; } set { _IdMayIn = value; OnPropertyChanged("IdMayIn"); } }
        public Nullable<int> Status { get { return _Status; } set { _Status = value; OnPropertyChanged("Status"); } }
        public Nullable<System.DateTime> CreatedAt { get { return _CreatedAt; } set { _CreatedAt = value; OnPropertyChanged("CreatedAt"); } }
        public Nullable<System.DateTime> ModifiedAt { get { return _ModifiedAt; } set { _ModifiedAt = value; OnPropertyChanged("ModifiedAt"); } }


        public event PropertyChangedEventHandler PropertyChanged;
        protected void OnPropertyChanged([CallerMemberName] string name = null) {
            PropertyChanged?.Invoke(this, new PropertyChangedEventArgs(name));
        }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ChiTietHoaDon> ChiTietHoaDons { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ChiTietHoaDonTemp> ChiTietHoaDonTemps { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ChiTietPhieuNhap> ChiTietPhieuNhaps { get; set; }
        public virtual DanhMuc DanhMuc { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HuyMon> HuyMons { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Kho> Khoes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LuuKhuyenMai> LuuKhuyenMais { get; set; }
        public virtual MayIn MayIn { get; set; }
        public virtual Unit Unit { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SanPhamKhuyenMai> SanPhamKhuyenMais { get; set; }
    }
}
