//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyNhaHang.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SanPhamKhuyenMai
    {
        public int Id { get; set; }
        public string IdMon { get; set; }
        public Nullable<int> IdKhuyenMai { get; set; }
        public int Status { get; set; }
        public System.DateTime dateBatDau { get; set; }
        public System.TimeSpan timeBatDau { get; set; }
        public System.DateTime dateKetThuc { get; set; }
        public System.TimeSpan timeKetThuc { get; set; }
    
        public virtual KhuyenMai KhuyenMai { get; set; }
        public virtual Mon Mon { get; set; }
    }
}
